{% set name = "graphite2" %}
{% set version = "1.3.12" %}
{% set sha256 = "cd9530c16955c181149f9af1f13743643771cb920c75a04c95c77c871a2029d0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/silnrsi/graphite/releases/download/{{ version }}/{{ name }}-{{ version }}.tgz
  sha256: {{ sha256 }}

build:
  number: 2
  skip: true  # [win]
  run_exports:
    # Not sure if this is same, but https://abi-laboratory.pro/tracker/timeline/graphite/
    - {{ pin_subpackage('graphite2') }}


requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make


about:
  home: http://graphite.sil.org/
  license: LGPLv2
  license_file: COPYING
  summary: 'A "smart font" system that handles the complexities of lesser-known languages of the world.'

extra:
  recipe-maintainers:
    - pkgw
    - mingwandroid
    - ocefpaf
