travis:
  secure:
    BINSTAR_TOKEN: SQDJ+IOAE+Zho51lM4NGKbZEIRvgGTK0qSryBj9gOWCy2AADMiLtcikjjNnr2JWjh2J2JPIFcA8TC0cKDaCsCGz+dz9qNSN8dGoJTR32tPZ/wSU551YuURrAOe8juGO/x9Z3UJo7ENIqEXy6UWrUrKCPRp41Tnb+FHUUKyz/OzWXyXPEdS2eCjsPyY6mOwz8PiSnpN9hftJyWmYUIuXtNjYfWUwg9P8uiW3TxiqcP18WyBUgqHXhj2VwlG6W39fhgeDNWicwQNHtbyr1Q5pK6cdxPPYU9pakAz1F+iMKcMSmuKCO9hHDRF293EApZceTOF/Ctt6MmV6TPZZNns7XNx/aVr9zM/WmuHHkAh9Oc42pGTT0t04Mk1W8W1rN9QFeCA+wyyfXQG2DIMfmhPvhJdtvHv8yenNCHIRCqCQw3KoijSvElngr1bB6vFgydu6Yn7JI7aGBjP/BuXFtUueY72kt+y4cdc6n9dEsKal7eLJsoSHRce+a49uG7TSV0+XmGQpnjAaeEng3NWKO44nVCOTTkH01MxS3jbJbzrWk8EIavIe7BAHEvwOofJA0nFsprxwKDubpNTt85e2pg6RJNWsxLQvtRPcsYfRITKzYl+4AiWHbpVqBPjsnzEeSSjKAvP6x9DBSkMvsj7bHn09WrIu+DjvJP/lrDwEwCjpweAQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
